name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
        
      - name: Build application
        run: ./scripts/buildprod.sh
    
      - name: auth
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Push to GAR
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/${{ secrets.GCP_NOTELY_PROJECT_ID }}/notely-ar-repo/notely:latest .
    
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_NOTELY_PROJECT_ID }}/notely-ar-repo/notely:latest \
            --region us-central1 \
            --project ${{ secrets.GCP_NOTELY_PROJECT_ID }} \
            --max-instances 2 \
            --allow-unauthenticated 
